// Study content for "Beat the Geek" trivia night.
// likelihood: "high" | "medium" | "low" — our best guess at how likely something
// in this vein shows up as an actual question, based on how commonly it's used
// in bar trivia for this topic. Not a guarantee — study broadly, not narrowly.

const CATEGORIES = [
  {
    id: 'grand-stuff',
    name: 'Grand Stuff',
    shortName: 'Grand Stuff',
    blurb: 'A vague, punny category name almost always means wordplay on "Grand ___" or "things that are Grand." We covered the most common angles: geography, sports, food, cars, and pop culture.',
    infoBox: '<strong>Why this list looks broad:</strong> "Grand Stuff" could go a dozen directions. Rather than guess wrong, this covers the highest-frequency "Grand" trivia facts across categories so you have a fact ready no matter which angle the question takes.',
    type: 'quiz',
    items: [
      { q: 'What national park is home to a mile-deep gorge carved by the Colorado River?', a: 'Grand Canyon National Park (Arizona)', notes: 'Established as a national park in 1919.', likelihood: 'high' },
      { q: 'What NYC transit hub, opened in 1913, is famous for its celestial ceiling mural and four-faced brass clock?', a: 'Grand Central Terminal', notes: 'Located at 42nd St & Park Ave, Manhattan.', likelihood: 'medium' },
      { q: 'What Nashville venue and radio show, running continuously since 1925, is a shrine to country music?', a: 'The Grand Ole Opry', likelihood: 'medium' },
      { q: 'In tennis, what term covers the four biggest annual tournaments: Australian Open, French Open, Wimbledon, and the US Open?', a: 'A Grand Slam', likelihood: 'high' },
      { q: 'In baseball, what do you call a home run hit with the bases loaded?', a: 'A grand slam', likelihood: 'high' },
      { q: 'What Rockstar Games open-world franchise, set in places like Vice City and Los Santos, has sold over 400 million copies?', a: 'Grand Theft Auto (GTA)', likelihood: 'high' },
      { q: 'What do you call a full-size, horizontally strung piano, as opposed to an upright?', a: 'A grand piano', likelihood: 'medium' },
      { q: 'What word precedes "Prix" in the name of Formula 1\'s biggest races, like the ones in Monaco and Britain?', a: 'Grand Prix', likelihood: 'high' },
      { q: '"Grand Canyon State" is the nickname for which US state?', a: 'Arizona', likelihood: 'medium' },
      { q: 'What Jeep SUV model, first sold in 1992, shares its name with a famous canyon?', a: 'The Jeep Grand Cherokee', likelihood: 'medium' },
      { q: 'What French orange-flavored liqueur, made from cognac brandy and bitter orange peel, is a staple in a Cosmopolitan or Sidecar?', a: 'Grand Marnier', likelihood: 'low' },
      { q: 'Which small European country wedged between Belgium, France, and Germany is officially a "Grand Duchy"?', a: 'Luxembourg', likelihood: 'low' },
      { q: 'What notoriously difficult steeplechase horse race is run every April at Aintree Racecourse in England?', a: 'The Grand National', likelihood: 'low' },
      { q: 'What classic Denny\'s breakfast platter, introduced in 1977, includes eggs, meat, pancakes, and hash browns?', a: 'The Grand Slam Breakfast', likelihood: 'medium' },
      { q: 'What Washington State dam on the Columbia River is the largest hydroelectric power producer in the United States?', a: 'Grand Coulee Dam', notes: 'A Pacific Northwest tie-in worth knowing given the other categories this week.', likelihood: 'medium' },
      { q: 'What major river forms much of the border between Texas and Mexico?', a: 'The Rio Grande', likelihood: 'medium' },
      { q: 'What Wyoming mountain range and national park is home to the peak that gives it its name?', a: 'Grand Teton (Range / National Park)', likelihood: 'low' },
      { q: 'George M. Cohan\'s patriotic song calls the American flag "you\'re a ___"?', a: '"You\'re a Grand Old Flag"', likelihood: 'low' },
    ],
  },

  {
    id: 'seattle-sports',
    name: 'Seattle Pro Sports',
    shortName: 'Seattle Sports',
    blurb: 'Seahawks, Mariners, Kraken, Sounders, Storm, and the ghost of the SuperSonics — highlight-reel facts plus a batch of deeper-cut ones for a "geek"-level crowd.',
    type: 'quiz',
    items: [
      { q: 'What year did the Seattle Seahawks win their only Super Bowl, and who did they beat?', a: 'Super Bowl XLVIII, February 2014 — beat the Denver Broncos 43–8', likelihood: 'high' },
      { q: 'What nickname is given to the Seahawks\' famously loud fan base, whose jersey number (12) is retired?', a: 'The 12th Man ("the 12s")', likelihood: 'high' },
      { q: 'What nickname described the Seahawks\' dominant early-2010s secondary, including Richard Sherman, Earl Thomas, and Kam Chancellor?', a: 'The Legion of Boom', likelihood: 'high' },
      { q: 'Who was the Seahawks\' head coach for their Super Bowl XLVIII win, and remains their coach today?', a: 'Pete Carroll', likelihood: 'high' },
      { q: 'Which Seahawks running back is known for the "Beast Mode" nickname and touchdown celebrations?', a: 'Marshawn Lynch', likelihood: 'high' },
      { q: 'What is the current name of the Seahawks and Sounders\' downtown stadium (formerly Qwest Field, then CenturyLink Field)?', a: 'Lumen Field', likelihood: 'medium' },
      { q: 'Which Mariners outfielder set the MLB single-season hits record with 262 hits in 2004?', a: 'Ichiro Suzuki', likelihood: 'high' },
      { q: 'Which Mariners center fielder and Hall of Famer, son of a former MLB All-Star, was known as "The Kid"?', a: 'Ken Griffey Jr.', likelihood: 'high' },
      { q: 'The Mariners are the only original MLB franchise to have never done what?', a: 'Reached (played in) a World Series', likelihood: 'medium' },
      { q: 'Which Mariners DH/third baseman, nicknamed "Mr. Mariner," hit "The Double" in the 1995 ALDS, credited with helping save baseball in Seattle?', a: 'Edgar Martinez', likelihood: 'medium' },
      { q: 'What is the Mariners\' home ballpark called today?', a: 'T-Mobile Park (formerly Safeco Field)', likelihood: 'medium' },
      { q: 'Seattle\'s NHL expansion team began play in the 2021–22 season — what is it named?', a: 'The Seattle Kraken', likelihood: 'high' },
      { q: 'What arena, built on the site of the old Seattle Center Coliseum/KeyArena, is home to the Kraken?', a: 'Climate Pledge Arena', likelihood: 'medium' },
      { q: 'Seattle\'s MLS team has won two MLS Cups, in 2016 and 2019 — name the team.', a: 'Seattle Sounders FC', likelihood: 'medium' },
      { q: 'Name the Seattle Storm point guard who retired in 2022 after 21 seasons, all with Seattle, and 4 WNBA championships.', a: 'Sue Bird', likelihood: 'high' },
      { q: 'Name the Storm forward, UConn alum, 2x WNBA champion in Seattle, and multiple-time Olympic gold medalist.', a: 'Breanna Stewart', likelihood: 'medium' },
      { q: 'The Seattle SuperSonics won their only NBA championship in what year, and under which head coach?', a: '1979, coached by Lenny Wilkens', likelihood: 'high' },
      { q: 'Name the star point guard ("The Glove") and power forward ("Reign Man") who led the Sonics to the 1996 NBA Finals.', a: 'Gary Payton and Shawn Kemp', likelihood: 'medium' },
      { q: 'In what year did the SuperSonics relocate to become the Oklahoma City Thunder?', a: '2008', likelihood: 'high' },
      { q: 'True or false: the Seahawks have always played in the NFC West.', a: 'False — after one season in the NFC West (1976), they spent 1977–2001 in the AFC West before moving back to the NFC West for the 2002 league realignment.', notes: 'A classic "gotcha" — most casual fans assume they were always NFC.', likelihood: 'low' },
      { q: 'Which Hall of Fame Seahawks wide receiver played his entire 14-year career (1976–1989) in Seattle and retired with the NFL\'s all-time records for career receptions, receiving yards, and receiving touchdowns?', a: 'Steve Largent', notes: 'His reception record (819) was later broken by Jerry Rice.', likelihood: 'medium' },
      { q: 'Which Seahawks defensive tackle won NFL Defensive Player of the Year in 1992 despite the team going 2–14 that season?', a: 'Cortez Kennedy', likelihood: 'low' },
      { q: 'Where did the Seahawks play home games in 2000 and 2001 while their new stadium (now Lumen Field) was under construction?', a: 'Husky Stadium, on the University of Washington campus', likelihood: 'low' },
      { q: 'The Mariners\' 2001 team won 116 regular-season games — tying which historic team for the all-time single-season wins record?', a: 'The 1906 Chicago Cubs', likelihood: 'medium' },
      { q: 'Randy Johnson threw his first career no-hitter for the Mariners in 1990. The Mariners later traded him mid-1998 to which team, kicking off his run of World Series success?', a: 'The Houston Astros', likelihood: 'medium' },
      { q: 'Legendary Mariners radio broadcaster Dave Niehaus, known for "My oh my!", called Mariners games for how many seasons, and in what year did he win the Baseball Hall of Fame\'s Ford C. Frick Award?', a: '34 seasons (1977–2010); won the Frick Award in 2008', likelihood: 'medium' },
      { q: 'The Seattle SuperSonics\' name, chosen for their 1967 inaugural season, is a nod to what local industry/program?', a: 'Boeing and its supersonic transport (SST) program', notes: 'A point of local civic pride at the time; the federal SST program was later cancelled in 1971.', likelihood: 'medium' },
      { q: 'Who scored the Seattle Kraken\'s first-ever regular season goal, in their October 2021 season opener against the Vegas Golden Knights?', a: 'Ryan Donato', notes: 'Jared McCann scored their second goal (a power play) in that same game, a 4–3 loss.', likelihood: 'low' },
      { q: 'Before Seattle Sounders FC joined MLS in 2009, an earlier "Seattle Sounders" club played in the NASL. Roughly what years was that original team active?', a: '1974–1983', likelihood: 'low' },
      { q: 'Storm legend Lauren Jackson, a three-time WNBA MVP from Australia, was the #1 overall pick in what year\'s WNBA Draft?', a: '2001', likelihood: 'medium' },
    ],
  },

  {
    id: 'music-girl-bands',
    name: 'Music – Girl Bands',
    shortName: 'Music',
    blurb: 'The highest-value round to drill: you need both title and artist, and it\'s much easier to lock in once you\'ve actually heard the hook. Press play on each.',
    infoBox: '<strong>How to use this:</strong> hit play, see how fast you can name the song + artist before the reveal, then check yourself. Every video ID below was individually verified against the live YouTube page. Each track also jumps past most of the intro (<code>startSeconds</code> below) so you land closer to the recognizable part rather than a video preamble or long instrumental — these are estimates, so nudge the number for any track that feels off.',
    type: 'music',
    items: [
      { title: 'Wannabe', artist: 'Spice Girls', youtubeId: 'gJLIiF15wjQ', startSeconds: 0, likelihood: 'high', notes: 'Arguably THE girl-group song. Know all five Spice Girls: Mel B (Scary), Mel C (Sporty), Emma (Baby), Geri (Ginger), Victoria (Posh).' },
      { title: 'Say My Name', artist: "Destiny's Child", youtubeId: 'sQgd6MccwZc', startSeconds: 0, likelihood: 'high', notes: 'Final lineup: Beyoncé, Kelly Rowland, Michelle Williams.' },
      { title: 'No Scrubs', artist: 'TLC', youtubeId: 'FrLequ6dUdM', startSeconds: 0, likelihood: 'high', notes: 'TLC = Tionne "T-Boz", Lisa "Left Eye", Rozonda "Chilli".' },
      { title: 'Waterfalls', artist: 'TLC', youtubeId: '8WEtxJ4-sh4', startSeconds: 0, likelihood: 'high' },
      { title: 'Walk Like an Egyptian', artist: 'The Bangles', youtubeId: 'Cv6tuzHUuuk', startSeconds: 10, likelihood: 'high', notes: '1986 — one of the most recognizable hooks of the whole 80s.' },
      { title: 'Stop! In the Name of Love', artist: 'The Supremes', youtubeId: 'une981B7Q4Y', startSeconds: 5, likelihood: 'high', notes: 'Motown, 1965 — Diana Ross led this lineup. Official upload is a lyric video, no period music video exists.' },
      { title: 'Survivor', artist: "Destiny's Child", youtubeId: 'Wmc8bQoL-J0', startSeconds: 5, likelihood: 'medium' },
      { title: 'Spice Up Your Life', artist: 'Spice Girls', youtubeId: '9wfpXI5PKlw', startSeconds: 5, likelihood: 'medium' },
      { title: "My Lovin' (You're Never Gonna Get It)", artist: 'En Vogue', youtubeId: 'JIuYQ_4TcXg', startSeconds: 5, likelihood: 'medium' },
      { title: 'Cruel Summer', artist: 'Bananarama', youtubeId: 'cWN-Hw-mEns', startSeconds: 0, likelihood: 'medium' },
      { title: 'Hold On', artist: 'Wilson Phillips', youtubeId: 'uIbXvaE39wM', startSeconds: 10, likelihood: 'medium', notes: 'Trio of Carnie & Wendy Wilson (Beach Boys) and Chynna Phillips (Mamas & the Papas) — a good "family trivia" hook.' },
      { title: 'Never Ever', artist: 'All Saints', youtubeId: 'X28-olxweYk', startSeconds: 45, likelihood: 'medium', notes: 'Has an unusually long spoken/instrumental intro before the song proper kicks in — start is pushed later than most tracks here.' },
      { title: 'Black Magic', artist: 'Little Mix', youtubeId: 'MkElfR_NPBI', startSeconds: 8, likelihood: 'medium' },
      { title: 'Work from Home', artist: 'Fifth Harmony', youtubeId: '5GL9JoH4Sws', startSeconds: 5, likelihood: 'medium', notes: 'Fifth Harmony is Camila Cabello\'s pre-solo group.' },
      { title: 'Be My Baby', artist: 'The Ronettes', youtubeId: 'jSPpbOGnFgk', startSeconds: 0, likelihood: 'medium', notes: 'Led by Ronnie Spector; 1963. Official upload is audio-only, no music video exists. Don\'t skip the intro here — the drum intro IS the famous hook.' },
      { title: 'Goodbye Earl', artist: 'The Chicks', youtubeId: 'Gw7gNf_9njs', startSeconds: 0, likelihood: 'medium', notes: 'Formerly "Dixie Chicks." A country trio, not a pop/R&B girl group — but trivia writers often lump it into "girl band/group" rounds.' },
      { title: 'We Got the Beat', artist: "The Go-Go's", youtubeId: '_uQgkse0E04', startSeconds: 5, likelihood: 'medium', notes: 'Notable as an all-woman band that wrote and played their own instruments, not just vocalists.' },
      { title: 'Push the Button', artist: 'Sugababes', youtubeId: 'oJDGcxAf9D8', startSeconds: 10, likelihood: 'low', notes: 'Big in the UK, much less known to a US crowd — lower priority.' },
      { title: 'Sound of the Underground', artist: 'Girls Aloud', youtubeId: 'V9Wv4SCBiTE', startSeconds: 15, likelihood: 'low', notes: 'UK-only fame (X Factor-style show "Popstars: The Rivals") — lower priority for a US room.' },
      { title: 'The Wire', artist: 'HAIM', youtubeId: '1TffpkE2GU4', startSeconds: 10, likelihood: 'low', notes: 'More indie/critical darling than mainstream radio hit — lower priority.' },
    ],
  },

  {
    id: 'movie-quotes-2010s',
    name: '2010s Movie Quotes',
    shortName: 'Movie Quotes',
    blurb: 'Iconic, widely-quoted lines from movies released 2010–2019, plus a batch of harder deep-cuts for a "geek"-level crowd.',
    type: 'quiz',
    items: [
      { q: '"May the odds be ever in your favor." What 2012 film franchise made this Capitol catchphrase famous?', a: 'The Hunger Games', likelihood: 'high' },
      { q: '"We need to go deeper." What 2010 Christopher Nolan film about infiltrating dreams features this line?', a: 'Inception', likelihood: 'medium' },
      { q: '"Let it go, let it go, can\'t hold it back anymore." Elsa sings this anthem in what 2013 Disney film?', a: 'Frozen', likelihood: 'high' },
      { q: '"Do you want to build a snowman?" is sung by which character in Frozen (2013)?', a: 'Anna', likelihood: 'medium' },
      { q: '"I am Groot." is the only line ever spoken by which character, introduced in 2014?', a: 'Groot, from Guardians of the Galaxy', likelihood: 'high' },
      { q: '"Maximum effort." is the catchphrase of which wisecracking antihero from 2016?', a: 'Deadpool (Wade Wilson)', likelihood: 'high' },
      { q: '"What a lovely day!" is repeated by the villain Nux in what 2015 post-apocalyptic action film?', a: 'Mad Max: Fury Road', likelihood: 'medium' },
      { q: '"Wakanda forever!" is the rallying cry/salute from what 2018 Marvel film?', a: 'Black Panther', likelihood: 'high' },
      { q: '"Sell me this pen." Jordan Belfort challenges people with this line in what 2013 Scorsese film?', a: 'The Wolf of Wall Street', likelihood: 'medium' },
      { q: '"A million dollars isn\'t cool. You know what\'s cool? A billion dollars." is said by a fictionalized Sean Parker in what 2010 film about Facebook\'s founding?', a: 'The Social Network', likelihood: 'medium' },
      { q: '"The sunken place" is a chilling concept introduced in what 2017 Jordan Peele horror film?', a: 'Get Out', likelihood: 'high' },
      { q: '"Here\'s to the ones who dream, foolish as they may seem" is a line from what 2016 movie musical starring Emma Stone and Ryan Gosling?', a: 'La La Land', likelihood: 'medium' },
      { q: '"The D is silent." Django corrects the pronunciation of his name in what 2012 Tarantino western?', a: 'Django Unchained', likelihood: 'medium' },
      { q: '"It\'s not about deserve. It\'s about what you believe." is a defining line from what 2017 DC film, the title character\'s first solo movie?', a: 'Wonder Woman', likelihood: 'low' },
      { q: '"Not quite my tempo." is snapped by a demanding music instructor in what 2014 drumming drama?', a: 'Whiplash', likelihood: 'medium' },
      { q: 'The "cool girl" monologue about a fabricated persona features in what 2014 psychological thriller based on a Gillian Flynn novel?', a: 'Gone Girl', likelihood: 'medium' },
      { q: '"To infinity and beyond!" gets an emotional send-off in what 2010 Pixar sequel?', a: 'Toy Story 3', likelihood: 'high' },
      { q: '"I am Iron Man." is Tony Stark\'s final, sacrificial line in the climax of what 2019 Marvel film?', a: 'Avengers: Endgame', likelihood: 'high' },
      { q: '"Manners maketh man." is the signature line of Colin Firth\'s gentleman-spy character in what 2014 film?', a: 'Kingsman: The Secret Service (spoken by Harry Hart)', likelihood: 'medium' },
      { q: '"I\'m gonna have to science the s**t out of this." is said by a stranded astronaut in what 2015 Ridley Scott film?', a: 'The Martian (spoken by Mark Watney, played by Matt Damon)', likelihood: 'medium' },
      { q: 'In Ex Machina (2014), which character says "If you\'ve created a conscious machine, it\'s not the history of man. That\'s the history of gods"?', a: 'Caleb (played by Domhnall Gleeson)', notes: 'A commonly misattributed line — often wrongly credited to Nathan, the AI\'s creator, when it\'s actually Caleb reacting to him.', likelihood: 'low' },
      { q: '"I suspect foul play. I have eliminated no suspects." is a line from which detective in the 2019 whodunit Knives Out?', a: 'Benoit Blanc (played by Daniel Craig)', likelihood: 'medium' },
      { q: '"You\'re looking so well, darling, you really are." — Ralph Fiennes\' character says this in what 2014 Wes Anderson film?', a: 'The Grand Budapest Hotel (spoken by M. Gustave)', notes: 'The joke: he\'s saying it to a corpse, Madame D., in her open casket.', likelihood: 'low' },
      { q: '"Let\'s dance." are the final spoken words of the title character in what 2019 anti-hate satire, said to Elsa?', a: 'Jojo Rabbit', likelihood: 'low' },
    ],
  },

  {
    id: 'bonus',
    name: 'Bonus Question',
    shortName: 'Bonus',
    blurb: 'The named bonus question for this week.',
    type: 'quiz',
    items: [
      { q: 'Who was the last person to coach the Seattle SuperSonics?', a: 'P.J. Carlesimo', notes: 'His only season with the Sonics was 2007–08, a franchise-worst 20–62 record — the team\'s 41st and final season in Seattle before relocating to Oklahoma City to become the Thunder.', likelihood: 'high' },
    ],
  },
];
